CREATE DATABASE airbjdev
AUTOMATIC STORAGE YES
ON /db2data01/airbjdev
DBPATH ON /db2data01/airbjdev
USING CODESET UTF-8 TERRITORY GB
CATALOG   TABLESPACE
MANAGED BY AUTOMATIC STORAGE
USER      TABLESPACE
MANAGED BY AUTOMATIC STORAGE
TEMPORARY TABLESPACE
MANAGED BY AUTOMATIC STORAGE
#

