CREATE DATABASE AIRB_DEV
AUTOMATIC STORAGE YES
ON /db2data01/airb_dev
DBPATH ON /db2data01/airb_dev
USING CODESET UTF-8 TERRITORY GB
CATALOG   TABLESPACE
MANAGED BY AUTOMATIC STORAGE
USER      TABLESPACE
MANAGED BY AUTOMATIC STORAGE
TEMPORARY TABLESPACE
MANAGED BY AUTOMATIC STORAGE
#

