CREATE DATABASE AIRB_TST
AUTOMATIC STORAGE YES
ON /db2data01/airb_tst
DBPATH ON /db2data01/airb_tst
USING CODESET UTF-8 TERRITORY GB
CATALOG   TABLESPACE
MANAGED BY AUTOMATIC STORAGE
USER      TABLESPACE
MANAGED BY AUTOMATIC STORAGE
TEMPORARY TABLESPACE
MANAGED BY AUTOMATIC STORAGE
#

